### ISSUE TITLE
Render LaTeX output produced by code

### ISSUE THREAD

**Issue by HughGrovesArup** [microsoft/vscode-notebook-renderers#77] opened 2021-11-10 14:43 UTC
I have a python library that returns LaTeX equations, is there a way to get these to render in the vs-code notebook output?

![image](https://user-images.githubusercontent.com/40033911/141133926-a0d937ea-ad3b-4d02-a32b-bb3c89e20e87.png)

**Comment by DonJayamanne** [comment] 2021-11-11 21:41
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/7801

**Closed by DonJayamanne** 2021-11-11 21:41 UTC
