### ISSUE TITLE
Unable to change the font of Markdown cells of Jupyter notebook...

### ISSUE THREAD

**Issue by allabur** [microsoft/vscode-notebook-renderers#218] opened 2024-10-14 11:10 UTC
Hi, I was interested in changing the font type in the markdown cells of the jupyter notebook in vscode but I have not found a solution. I have seen that other people have also tried the same thing. I was wondering if writing it here was more appropriate. Is it possible that this option exists or was created?

- https://github.com/microsoft/vscode/issues/143907
- https://stackoverflow.com/questions/62580657/vs-code-jupyter-notebook-markdown-display-font

**Comment by DonJayamanne** [comment] 2024-10-14 11:14
Thank you for filling this issue,
Given the issue is still  open, we do not have a fix for this.
Closing as a duplicate of https://github.com/microsoft/vscode/issues/143907

**Closed by DonJayamanne** 2024-10-14 11:14 UTC
