### ISSUE TITLE
Expand Image gets stuck when showing a wide but short image

### ISSUE THREAD

**Issue by alanyoungCN** [microsoft/vscode-notebook-renderers#103] opened 2022-03-13 11:58 UTC
After I draw a very wide but short image to show a time series and click the Expand Image button, the preview will get stuck when I enlarge it and drag from right to left.
This is the full image and I can drag it well.
![image](https://user-images.githubusercontent.com/32586930/158058173-bdfcace3-8e9e-4d82-bf96-6efc716453e0.png)

But when I enlarge the image, I can't see the right part anyway.
![image](https://user-images.githubusercontent.com/32586930/158058220-81cbf5af-7fb3-454b-b655-6095128945e0.png)
The screenshot above is the rightest I can drag.

However, the left blank becomes more.
![image](https://user-images.githubusercontent.com/32586930/158058291-3c11c07b-b69c-4083-adbf-ae3933712319.png)

**Comment by alanyoungCN** [comment] 2022-03-13 12:48
please cc.. @DonJayamanne @joyceerhl  @joshua-maros

**Comment by DonJayamanne** [comment] 2022-03-15 19:36
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/9349

**Closed by DonJayamanne** 2022-03-15 19:36 UTC
